# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &static-analysis
      name: Analyze on SonarCloud
      caches:
        - sonar
      script:
        - set +u
        - pipe: sonarsource/sonarcloud-scan:0.1.5
          variable:
            SONAR_TOKEN: ${SONAR_TOKEN}
            EXTRA_ARGS: -Dsonar.projectKey=jorsay_nerd -Dsonar.organization=jorsay-bitbucket
        - set -u

pipelines:
  default:
    - step: *static-analysis
