version: "3.7"

services:
  mongodb:
    ports:
      - "${MONGODB_PORT_NUMBER}:${MONGODB_PORT_NUMBER}"
  rabbitmq:
    ports:
      - "${RABBITMQ_NODE_PORT_NUMBER}:${RABBITMQ_NODE_PORT_NUMBER}"
      - "${RABBITMQ_MANAGER_PORT_NUMBER}:${RABBITMQ_MANAGER_PORT_NUMBER}"
  app:
    image: nerd/app:latest
    build:
      context: ./app
      args:
        NERD_SPACY_MODEL: "${NERD_SPACY_MODEL}"
    ports:
      - "${NERD_APP_HTTP_PORT}:${NERD_APP_HTTP_PORT}"
      - "3000:3000"
    volumes:
      - ./app:/app
    command: ["web-dev"]
  worker:
    image: nerd/app:latest
    volumes:
      - ./app:/app
  flower:
    image: nerd/app:latest
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    volumes:
      - ./app:/app
  ui:
    image: nerd/ui:latest
    build:
      context: ./ui
    volumes:
      - ./ui/build:/app
