version: "3.7"

services:
  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - "27017:27017"
    restart: on-failure
    env_file: .env
    volumes:
      - mongodb-data:/bitnami

  redis:
    image: bitnami/redis:4.0
    ports:
      - "6379:6379"
    restart: on-failure
    env_file: .env
    volumes:
      - redis-data:/bitnami

  app:
    image: nerd/app:latest
    build:
      context: .
      args:
        PIPENV_ARGS: --dev
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    restart: on-failure
    init: true
    env_file: .env
    depends_on:
      - mongodb
      - redis
    command: ["web"]

  worker:
    image: nerd/app:latest
    build:
      context: .
      args:
        PIPENV_ARGS: --dev
    volumes:
      - ./app:/app
      - ./docker/volumes/models:/app/models
    restart: on-failure
    init: true
    env_file: .env
    depends_on:
      - app
    command: ["worker"]

  flower:
    image: nerd/app:latest
    build:
      context: .
      args:
        PIPENV_ARGS: --dev
    ports:
      - 5555:5555
    env_file: .env
    restart: on-failure
    init: true
    depends_on:
      - app
    command: ["flower"]

volumes:
  mongodb-data:
  redis-data:

