version: "3.7"

services:
  mongodb:
    ports:
      - "${MONGODB_PORT_NUMBER}:${MONGODB_PORT_NUMBER}"
  rabbitmq:
    ports:
      - "${RABBITMQ_NODE_PORT_NUMBER}:${RABBITMQ_NODE_PORT_NUMBER}"
      - "${RABBITMQ_MANAGER_PORT_NUMBER}:${RABBITMQ_MANAGER_PORT_NUMBER}"
  app:
    image: nerd/app:dev
    build:
      target: development
    volumes:
      - ./app:/app
    ports:
      - "${NERD_APP_HTTP_PORT}:${NERD_APP_HTTP_PORT}"
      - "3000:3000"
    command: ["web-dev"]
  worker:
    build:
        target: development
    volumes:
      - ./app:/app
  flower:
    build:
        target: development
    volumes:
      - ./app:/app
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
  ui:
    volumes:
      - ./ui/build:/app
volumes:
  mongodb-data:
    driver: local
    driver_opts:
      type: none
      device: '$PWD/.docker/mongodb-data'
      o: bind
  models-dir:
    driver: local
    driver_opts:
      type: none
      device: '$PWD/.docker/models-dir'
      o: bind
