version: "3.7"
services:
  nginx:
    image: bitnami/nginx:1.16
    restart: on-failure
    init: true
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ./ui/build:/app
      - ./docker/nginx/nerd.conf:/opt/bitnami/nginx/conf/server_blocks/nerd.conf:ro
  mongodb:
    image: bitnami/mongodb:4.0
    restart: on-failure
    init: true
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - mongodb-data:/bitnami
  rabbitmq:
    image: bitnami/rabbitmq:3.7
    restart: on-failure
    init: true
    stdin_open: true
    tty: true
    env_file:
      - .env
  app: &app
    image: nerd/app:latest
    build:
      context: .
      args:
        NERD_SPACY_MODEL: "${NERD_SPACY_MODEL}"
    restart: on-failure
    init: true
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
    command: ["web"]
  worker:
    <<: *app
    depends_on:
      - app
    command: ["worker", "vCURRENT"]
  flower:
    <<: *app
    depends_on:
      - app
    command: ["flower"]
volumes:
  mongodb-data:
