version: "3.7"
services:
  ui:
    image: docker.pkg.github.com/qcho/nerd/ui:latest
    restart: on-failure
    init: true
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - "8080:8080"
  mongodb:
    image: bitnami/mongodb:4.2
    restart: on-failure
    init: true
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - nerd_mongodb-data:/bitnami
  rabbitmq:
    image: bitnami/rabbitmq:3.7
    restart: on-failure
    init: true
    stdin_open: true
    tty: true
    env_file:
      - .env
  app: &app
    image: docker.pkg.github.com/qcho/nerd/app:latest
    restart: on-failure
    init: true
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - nerd_models-dir:/app/models
    depends_on:
      - mongodb
      - rabbitmq
    command: ["web"]
  worker:
    <<: *app
    depends_on:
      - app
    command: ["worker", "vCURRENT"]
  flower:
    <<: *app
    depends_on:
      - app
    command: ["flower"]
volumes:
  nerd_mongodb-data:
    external: true # external to avoid deletion on docker-compose down
  # Models dir to share models between app & workers
  nerd_models-dir:
    external: true # external to avoid deletion on docker-compose down
