version: "3.7"

services:
  mongodb:
    ports:
      - "${MONGODB_PORT_NUMBER}:${MONGODB_PORT_NUMBER}"
  rabbitmq:
    ports:
      - "${RABBITMQ_NODE_PORT_NUMBER}:${RABBITMQ_NODE_PORT_NUMBER}"
      - "${RABBITMQ_MANAGER_PORT_NUMBER}:${RABBITMQ_MANAGER_PORT_NUMBER}"
  app:
    image: nerd/app:dev
    build:
      args:
        PIPENV_ARGS: --dev
    volumes:
      - ./app:/app
    ports:
      - "${NERD_APP_HTTP_PORT}:${NERD_APP_HTTP_PORT}"
      - "3000:3000"
  worker:
    build:
      args:
        PIPENV_ARGS: --dev
    volumes:
      - ./app:/app
  flower:
    build:
      args:
        PIPENV_ARGS: --dev
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
