@startuml

XDWeb --> Tagger : Get models
Tagger --> XDWeb : Models
XDWeb --> Tagger : Get tags for news and model
Tagger --> Tagger : Load model
Tagger --> Tagger : Infer tags
Tagger --> XDWeb: list of (entity, type)

@enduml
